/**
 * Wildfire perimeter history queries.
 *
 * OWNER: Agent B. Server side only. Reads data/fire-perimeters.geojson off
 * disk with node:fs. Do not import this from a client component.
 *
 * The committed extract is CAL FIRE FRAP perimeters, California only, 2006
 * onward, regenerated by scripts/build-fire-perimeters.mjs. See lib/fire-source.ts
 * for the citation text that must accompany any value this module returns.
 *
 * PROJECTION, the thing most likely to silently break this file: turf.js works
 * in WGS84 decimal degrees. The CAL FIRE source layer is EPSG:3857 (Web
 * Mercator, units of metres), and if those coordinates reach turf unconverted
 * every distance comes back wrong by orders of magnitude without throwing. The
 * build script forces outSR=4326 at fetch time, and assertWgs84 below fails
 * loudly at load if a future extract ever regresses on that.
 */

import fs from 'node:fs';
import path from 'node:path';

import booleanPointInPolygon from '@turf/boolean-point-in-polygon';
import pointToLineDistance from '@turf/point-to-line-distance';
import { lineString, point } from '@turf/helpers';
import type { Feature, MultiPolygon, Polygon, Position } from 'geojson';

import { SEARCH_RADIUS_MILES } from './fire-source';
import type { FireHistoryCheck } from './types';

interface PerimeterProperties {
  name: string;
  year: number | null;
  acres: number | null;
  alarmDate: string | null;
}

type PerimeterFeature = Feature<Polygon | MultiPolygon, PerimeterProperties> & {
  bbox: [number, number, number, number];
};

interface PerimeterCollection {
  type: 'FeatureCollection';
  metadata: Record<string, unknown>;
  features: PerimeterFeature[];
}

const DATA_PATH = path.join(process.cwd(), 'data', 'fire-perimeters.geojson');

/** California's bounding box in WGS84, padded. If the extract is in any other
 *  CRS the coordinates fall wildly outside this and we want to know at load
 *  time, not after shipping a letter with a fabricated distance in it. */
const CA_BOUNDS = { minLng: -125.5, maxLng: -113.5, minLat: 32.0, maxLat: 42.5 };

function assertWgs84(features: PerimeterFeature[]): void {
  const sample = features.slice(0, 50);
  for (const f of sample) {
    const minLng = f.bbox[0];
    const minLat = f.bbox[1];
    const maxLng = f.bbox[2];
    const maxLat = f.bbox[3];
    const ok =
      minLng >= CA_BOUNDS.minLng &&
      maxLng <= CA_BOUNDS.maxLng &&
      minLat >= CA_BOUNDS.minLat &&
      maxLat <= CA_BOUNDS.maxLat;
    if (!ok) {
      throw new Error(
        `fire-perimeters.geojson does not look like WGS84 degrees inside California ` +
          `(saw bbox ${f.bbox.join(', ')} on "${f.properties.name}"). ` +
          `Rebuild it with scripts/build-fire-perimeters.mjs, which forces outSR=4326.`,
      );
    }
  }
}

let cache: PerimeterCollection | null = null;

/** Loaded once per server process. ~6 MB of JSON, so parsing it per request
 *  would dominate the response time. */
function loadPerimeters(): PerimeterCollection {
  if (cache) return cache;
  const parsed = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8')) as PerimeterCollection;
  if (!parsed.features?.length) {
    throw new Error('fire-perimeters.geojson contains no features.');
  }
  assertWgs84(parsed.features);
  cache = parsed;
  return parsed;
}

const MILES_PER_DEGREE_LAT = 69.0;

/** Cheap rejection test before the expensive geometry work. Expands the
 *  feature's bounding box by the search radius and asks whether the parcel
 *  could possibly fall inside. Longitude degrees shrink with latitude, hence
 *  the cosine term. */
function withinPaddedBbox(
  bbox: [number, number, number, number],
  lng: number,
  lat: number,
  radiusMiles: number,
): boolean {
  const padLat = radiusMiles / MILES_PER_DEGREE_LAT;
  const cos = Math.cos((lat * Math.PI) / 180);
  const padLng = radiusMiles / (MILES_PER_DEGREE_LAT * Math.max(cos, 0.1));
  return (
    lng >= bbox[0] - padLng &&
    lng <= bbox[2] + padLng &&
    lat >= bbox[1] - padLat &&
    lat <= bbox[3] + padLat
  );
}

function* ringsOf(geometry: Polygon | MultiPolygon): Generator<Position[]> {
  if (geometry.type === 'Polygon') {
    for (const ring of geometry.coordinates) yield ring;
  } else {
    for (const poly of geometry.coordinates) for (const ring of poly) yield ring;
  }
}

/**
 * Miles from the parcel to the nearest point on this fire's perimeter.
 * Zero when the parcel sits inside the burn scar, which is the strongest
 * possible evidence that an insurer's wildfire flag is justified.
 */
function distanceToPerimeterMiles(
  parcel: ReturnType<typeof point>,
  feature: PerimeterFeature,
): number {
  if (booleanPointInPolygon(parcel, feature.geometry)) return 0;

  let nearest = Infinity;
  for (const ring of ringsOf(feature.geometry)) {
    if (ring.length < 2) continue;
    const d = pointToLineDistance(parcel, lineString(ring), { units: 'miles' });
    if (d < nearest) nearest = d;
  }
  return nearest;
}

/**
 * Nearest recorded fire perimeter to a parcel.
 *
 * Returns null when nothing is within the search radius. That is a legitimate
 * result and the single most useful one for an appeal: it is affirmative
 * evidence that no recorded fire has reached this parcel's neighbourhood in
 * the covered window, not an error.
 *
 * Ties are broken toward the more recent fire, so a parcel sitting inside
 * overlapping burn scars is reported against the most recent one.
 */
export async function nearestFirePerimeter(
  coordinates: { lat: number; lng: number },
  radiusMiles: number = SEARCH_RADIUS_MILES,
): Promise<FireHistoryCheck | null> {
  const { lat, lng } = coordinates;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
    throw new Error(`nearestFirePerimeter needs finite coordinates, got ${lat}, ${lng}`);
  }
  if (Math.abs(lat) > 90 || Math.abs(lng) > 180) {
    throw new Error(
      `Coordinates ${lat}, ${lng} are outside WGS84 range. ` +
        `They are probably projected metres, not degrees.`,
    );
  }

  const { features } = loadPerimeters();
  const parcel = point([lng, lat]);

  let best: { feature: PerimeterFeature; miles: number } | null = null;

  for (const feature of features) {
    if (!withinPaddedBbox(feature.bbox, lng, lat, radiusMiles)) continue;

    const miles = distanceToPerimeterMiles(parcel, feature);
    if (miles > radiusMiles) continue;

    if (
      !best ||
      miles < best.miles - 1e-9 ||
      (Math.abs(miles - best.miles) <= 1e-9 &&
        (feature.properties.year ?? 0) > (best.feature.properties.year ?? 0))
    ) {
      best = { feature, miles };
    }
  }

  if (!best) return null;

  return {
    // Reported to a tenth of a mile: finer than that would overstate the
    // precision of generalized perimeter geometry.
    nearestPerimeterDistanceMiles: Math.round(best.miles * 10) / 10,
    nearestPerimeterYear: best.feature.properties.year ?? 0,
    perimeterName: `${best.feature.properties.name} Fire`,
  };
}

/**
 * Every recorded fire whose perimeter falls within radiusMiles, most recent
 * first. Used to characterise a neighbourhood rather than a single nearest
 * event: one fire eight miles out reads very differently from eleven.
 */
export async function firesWithinRadius(
  coordinates: { lat: number; lng: number },
  radiusMiles: number = SEARCH_RADIUS_MILES,
): Promise<Array<{ name: string; year: number; distanceMiles: number; acres: number | null }>> {
  const { lat, lng } = coordinates;
  const { features } = loadPerimeters();
  const parcel = point([lng, lat]);

  const hits: Array<{ name: string; year: number; distanceMiles: number; acres: number | null }> = [];
  for (const feature of features) {
    if (!withinPaddedBbox(feature.bbox, lng, lat, radiusMiles)) continue;
    const miles = distanceToPerimeterMiles(parcel, feature);
    if (miles > radiusMiles) continue;
    hits.push({
      name: `${feature.properties.name} Fire`,
      year: feature.properties.year ?? 0,
      distanceMiles: Math.round(miles * 10) / 10,
      acres: feature.properties.acres,
    });
  }

  hits.sort((a, b) => b.year - a.year || a.distanceMiles - b.distanceMiles);
  return hits;
}
